export let defaultHeros = [
    { name: 'Anduin', urlName: 'anduin', selected: false, banned: false },
    { name: 'Imperius', urlName: 'imperius', selected: false, banned: false },
    { name: 'Orphea', urlName: 'orphea', selected: false, banned: false },
    { name: "Mal'Ganis", urlName: 'malganis', selected: false, banned: false },
    { name: 'Mephisto', urlName: 'mephisto', selected: false, banned: false },
    { name: 'Whitemane', urlName: 'whitemane', selected: false, banned: false },
    { name: 'Yrel', urlName: 'yrel', selected: false, banned: false },
    { name: 'Deckard', urlName: 'deckard', selected: false, banned: false },
    { name: 'Fenix', urlName: 'fenix', selected: false, banned: false },
    { name: 'Maiev', urlName: 'maiev', selected: false, banned: false },
    { name: 'Blaze', urlName: 'blaze', selected: false, banned: false },
    { name: 'Hanzo', urlName: 'hanzo', selected: false, banned: false },
    { name: 'Alexstrasza', urlName: 'alexstrasza', selected: false, banned: false },
    { name: 'Junkrat', urlName: 'junkrat', selected: false, banned: false },
    { name: 'Ana', urlName: 'ana', selected: false, banned: false },
    { name: "Kel'Thuzad", urlName: 'kelthuzad', selected: false, banned: false },
    { name: 'Garrosh', urlName: 'garrosh', selected: false, banned: false },
    { name: 'Stukov', urlName: 'stukov', selected: false, banned: false },
    { name: 'Malthael', urlName: 'malthael', selected: false, banned: false },
    { name: 'D.Va', urlName: 'dva', selected: false, banned: false },
    { name: 'Genji', urlName: 'genji', selected: false, banned: false },
    { name: 'Cassia', urlName: 'cassia', selected: false, banned: false },
    { name: 'Probius', urlName: 'probius', selected: false, banned: false },
    { name: 'Lúcio', urlName: 'lucio', selected: false, banned: false },
    { name: 'Valeera', urlName: 'valeera', selected: false, banned: false },
    { name: "Zul'jin", urlName: 'zuljin', selected: false, banned: false },
    { name: 'Ragnaros', urlName: 'ragnaros', selected: false, banned: false },
    { name: 'Varian', urlName: 'varian', selected: false, banned: false },
    { name: 'Samuro', urlName: 'samuro', selected: false, banned: false },
    { name: 'Zarya', urlName: 'zarya', selected: false, banned: false },
    { name: 'Alarak', urlName: 'alarak', selected: false, banned: false },
    { name: 'Auriel', urlName: 'auriel', selected: false, banned: false },
    { name: "Gul'dan", urlName: 'guldan', selected: false, banned: false },
    { name: 'Medivh', urlName: 'medivh', selected: false, banned: false },
    { name: 'Chromie', urlName: 'chromie', selected: false, banned: false },
    { name: 'Tracer', urlName: 'tracer', selected: false, banned: false },
    { name: 'Dehaka', urlName: 'dehaka', selected: false, banned: false },
    { name: 'Xul', urlName: 'xul', selected: false, banned: false },
    { name: 'Li-Ming', urlName: 'li-ming', selected: false, banned: false },
    { name: 'Greymane', urlName: 'greymane', selected: false, banned: false },
    { name: 'Lunara', urlName: 'lunara', selected: false, banned: false },
    { name: 'Cho', urlName: 'cho', selected: false, banned: false },
    { name: 'Gall', urlName: 'gall', selected: false, banned: false },
    { name: 'Artanis', urlName: 'artanis', selected: false, banned: false },
    { name: 'Lt. Morales', urlName: 'lt-morales', selected: false, banned: false },
    { name: 'Rexxar', urlName: 'rexxar', selected: false, banned: false },
    { name: 'Kharazim', urlName: 'kharazim', selected: false, banned: false },
    { name: 'Leoric', urlName: 'leoric', selected: false, banned: false },
    { name: 'The Butcher', urlName: 'the-butcher', selected: false, banned: false },
    { name: 'Johanna', urlName: 'johanna', selected: false, banned: false },
    { name: "Kael'thas", urlName: 'kaelthas', selected: false, banned: false },
    { name: 'Sylvanas', urlName: 'sylvanas', selected: false, banned: false },
    {
        name: 'The Lost Vikings',
        urlName: 'the-lost-vikings',
        selected: false,
        banned: false,
    },
    { name: 'Thrall', urlName: 'thrall', selected: false, banned: false },
    { name: 'Jaina', urlName: 'jaina', selected: false, banned: false },
    { name: 'Azmodan', urlName: 'azmodan', selected: false, banned: false },
    { name: "Anub'arak", urlName: 'anubarak', selected: false, banned: false },
    { name: 'Chen', urlName: 'chen', selected: false, banned: false },
    { name: 'Rehgar', urlName: 'rehgar', selected: false, banned: false },
    { name: 'Zagara', urlName: 'zagara', selected: false, banned: false },
    { name: 'Murky', urlName: 'murky', selected: false, banned: false },
    { name: 'Brightwing', urlName: 'brightwing', selected: false, banned: false },
    { name: 'Li Li', urlName: 'li-li', selected: false, banned: false },
    { name: 'Tychus', urlName: 'tychus', selected: false, banned: false },
    { name: 'Abathur', urlName: 'abathur', selected: false, banned: false },
    { name: 'Arthas', urlName: 'arthas', selected: false, banned: false },
    { name: 'Diablo', urlName: 'diablo', selected: false, banned: false },
    { name: 'Illidan', urlName: 'illidan', selected: false, banned: false },
    { name: 'Kerrigan', urlName: 'kerrigan', selected: false, banned: false },
    { name: 'Malfurion', urlName: 'malfurion', selected: false, banned: false },
    { name: 'Muradin', urlName: 'muradin', selected: false, banned: false },
    { name: 'Nazeebo', urlName: 'nazeebo', selected: false, banned: false },
    { name: 'Nova', urlName: 'nova', selected: false, banned: false },
    { name: 'Raynor', urlName: 'raynor', selected: false, banned: false },
    { name: 'Sgt. Hammer', urlName: 'sgt-hammer', selected: false, banned: false },
    { name: 'Sonya', urlName: 'sonya', selected: false, banned: false },
    { name: 'Tyrael', urlName: 'tyrael', selected: false, banned: false },
    { name: 'Tyrande', urlName: 'tyrande', selected: false, banned: false },
    { name: 'Uther', urlName: 'uther', selected: false, banned: false },
    { name: 'Valla', urlName: 'valla', selected: false, banned: false },
    { name: 'Zeratul', urlName: 'zeratul', selected: false, banned: false },
    { name: 'E.T.C.', urlName: 'etc', selected: false, banned: false },
    { name: 'Falstad', urlName: 'falstad', selected: false, banned: false },
    { name: 'Gazlowe', urlName: 'gazlowe', selected: false, banned: false },
    { name: 'Stitches', urlName: 'stitches', selected: false, banned: false },
    { name: 'Tassadar', urlName: 'tassadar', selected: false, banned: false },
]
