export let defaultMaps = [
  { name: 'Alterac Pass', urlName: 'alterac-pass' },
  { name: 'Garden of Terror', urlName: 'garden-of-terror' },
  { name: 'Hanamura Temple', urlName: 'hanamura' },
  { name: 'Volskaya Foundry', urlName: 'volskaya' },
  { name: 'Haunted Mines', urlName: 'haunted-mines' },
  { name: 'Towers of Doom', urlName: 'towers-of-doom' },
  { name: 'Infernal Shrines', urlName: 'infernal-shrines' },
  { name: 'Battlefield of Eternity', urlName: 'battlefield-of-eternity' },
  { name: 'Tomb of the Spider Queen', urlName: 'tomb-of-the-spider-queen' },
  { name: 'Sky Temple', urlName: 'sky-temple' },
  { name: "Blackheart's Bay", urlName: 'blackhearts-bay' },
  { name: 'Dragon Shire', urlName: 'dragon-shire' },
  { name: 'Cursed Hollow', urlName: 'cursed-hollow' },
  { name: 'Braxis Holdout', urlName: 'braxis-holdout' },
  { name: 'Warhead Junction', urlName: 'warhead-junction' },
]

export let defaultHeros = [
  { name: 'Anduin', urlName: 'anduin' },
  { name: 'Imperius', urlName: 'imperius' },
  { name: 'Orphea', urlName: 'orphea' },
  { name: "Mal'Ganis", urlName: 'malganis' },
  { name: 'Mephisto', urlName: 'mephisto' },
  { name: 'Whitemane', urlName: 'whitemane' },
  { name: 'Yrel', urlName: 'yrel' },
  { name: 'Deckard', urlName: 'deckard' },
  { name: 'Fenix', urlName: 'fenix' },
  { name: 'Maiev', urlName: 'maiev' },
  { name: 'Blaze', urlName: 'blaze' },
  { name: 'Hanzo', urlName: 'hanzo' },
  { name: 'Alexstrasza', urlName: 'alexstrasza' },
  { name: 'Junkrat', urlName: 'junkrat' },
  { name: 'Ana', urlName: 'ana' },
  { name: "Kel'Thuzad", urlName: 'kelthuzad' },
  { name: 'Garrosh', urlName: 'garrosh' },
  { name: 'Stukov', urlName: 'stukov' },
  { name: 'Malthael', urlName: 'malthael' },
  { name: 'D.Va', urlName: 'dva' },
  { name: 'Genji', urlName: 'genji' },
  { name: 'Cassia', urlName: 'cassia' },
  { name: 'Probius', urlName: 'probius' },
  { name: 'Lúcio', urlName: 'lucio' },
  { name: 'Valeera', urlName: 'valeera' },
  { name: "Zul'jin", urlName: 'zuljin' },
  { name: 'Ragnaros', urlName: 'ragnaros' },
  { name: 'Varian', urlName: 'varian' },
  { name: 'Samuro', urlName: 'samuro' },
  { name: 'Zarya', urlName: 'zarya' },
  { name: 'Alarak', urlName: 'alarak' },
  { name: 'Auriel', urlName: 'auriel' },
  { name: "Gul'dan", urlName: 'guldan' },
  { name: 'Medivh', urlName: 'medivh' },
  { name: 'Chromie', urlName: 'chromie' },
  { name: 'Tracer', urlName: 'tracer' },
  { name: 'Dehaka', urlName: 'dehaka' },
  { name: 'Xul', urlName: 'xul' },
  { name: 'Li-Ming', urlName: 'li-ming' },
  { name: 'Greymane', urlName: 'greymane' },
  { name: 'Lunara', urlName: 'lunara' },
  { name: 'Cho', urlName: 'cho' },
  { name: 'Gall', urlName: 'gall' },
  { name: 'Artanis', urlName: 'artanis' },
  { name: 'Lt. Morales', urlName: 'lt-morales' },
  { name: 'Rexxar', urlName: 'rexxar' },
  { name: 'Kharazim', urlName: 'kharazim' },
  { name: 'Leoric', urlName: 'leoric' },
  { name: 'The Butcher', urlName: 'the-butcher' },
  { name: 'Johanna', urlName: 'johanna' },
  { name: "Kael'thas", urlName: 'kaelthas' },
  { name: 'Sylvanas', urlName: 'sylvanas' },
  {
    name: 'The Lost Vikings',
    urlName: 'the-lost-vikings',
  },
  { name: 'Thrall', urlName: 'thrall' },
  { name: 'Jaina', urlName: 'jaina' },
  { name: 'Azmodan', urlName: 'azmodan' },
  { name: "Anub'arak", urlName: 'anubarak' },
  { name: 'Chen', urlName: 'chen' },
  { name: 'Rehgar', urlName: 'rehgar' },
  { name: 'Zagara', urlName: 'zagara' },
  { name: 'Murky', urlName: 'murky' },
  { name: 'Brightwing', urlName: 'brightwing' },
  { name: 'Li Li', urlName: 'li-li' },
  { name: 'Tychus', urlName: 'tychus' },
  { name: 'Abathur', urlName: 'abathur' },
  { name: 'Arthas', urlName: 'arthas' },
  { name: 'Diablo', urlName: 'diablo' },
  { name: 'Illidan', urlName: 'illidan' },
  { name: 'Kerrigan', urlName: 'kerrigan' },
  { name: 'Malfurion', urlName: 'malfurion' },
  { name: 'Muradin', urlName: 'muradin' },
  { name: 'Nazeebo', urlName: 'nazeebo' },
  { name: 'Nova', urlName: 'nova' },
  { name: 'Raynor', urlName: 'raynor' },
  { name: 'Sgt. Hammer', urlName: 'sgt-hammer' },
  { name: 'Sonya', urlName: 'sonya' },
  { name: 'Tyrael', urlName: 'tyrael' },
  { name: 'Tyrande', urlName: 'tyrande' },
  { name: 'Uther', urlName: 'uther' },
  { name: 'Valla', urlName: 'valla' },
  { name: 'Zeratul', urlName: 'zeratul' },
  { name: 'E.T.C.', urlName: 'etc' },
  { name: 'Falstad', urlName: 'falstad' },
  { name: 'Gazlowe', urlName: 'gazlowe' },
  { name: 'Stitches', urlName: 'stitches' },
  { name: 'Tassadar', urlName: 'tassadar' },
]
